Repository AirDnS/airDns-front, pull requests merged in 2024-01, with the labels that each got.

#3 Feat/home page
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/assets/temp_room_img.png
  src/components/HelloWorld.vue
  src/components/Home/HomeFooter.vue
  src/components/Home/HomeHeader.vue
  src/components/Room/RoomFilter.vue
  src/components/Room/RoomList.vue
  src/components/Room/RoomMain.vue
  src/components/Room/RoomSearch.vue
  src/plugins/vuetify.js
Labels: enhancement

#4 Feat/home page
  package-lock.json
  package.json
  src/App.vue
  src/assets/temp_room_img.png
  src/components/home/HomeFooter.vue
  src/components/home/HomeHeader.vue
  src/components/home/HomeMain.vue
  src/components/room/RoomFilter.vue
  src/components/room/RoomList.vue
  src/components/room/RoomSearch.vue
  src/components/user/UserLogin.vue
  src/main.js
  src/routers/index.js
Labels: enhancement

#7 Feat : "방 정보 상세 설명 틀 구현"
  src/App.vue
  src/components/login/LoginHeader.vue
  src/components/login/LoginMain.vue
  src/components/room/RoomList.vue
  src/components/roomdetail/RoomDetailFooter.vue
  src/components/roomdetail/RoomDetailHeader.vue
  src/components/roomdetail/RoomDetailMain.vue
  src/components/roomdetail/RoomLike.vue
  src/components/roomdetail/RoomReservation.vue
  src/routers/index.js
Labels: enhancement

#10 Feat : "예약 확인 뼈대 구현"
  public/index.html
  src/components/reservation/ReservationCheckHeader.vue
  src/components/reservation/ReservationCheckMain.vue
  src/components/roomdetail/RoomDetailFooter.vue
  src/components/roomdetail/RoomReservation.vue
  src/routers/index.js
Labels: enhancement

#16 Feat: 결제창 연동
  package-lock.json
  package.json
  src/components/payment/CheckoutView.vue
  src/components/payment/SuccessView.vue
  src/components/reservation/ReservationCheckMain.vue
  src/confirmPayment.js
  src/routers/index.js
Labels: enhancement

#21 Feat : “유저 정보 조회 프론트”
  src/components/home/HomeHeader.vue
  src/components/userdetail/UserDetailHeader.vue
  src/components/userdetail/UserDetailMain.vue
  src/routers/index.js
Labels: enhancement

#22 Feat : "로그인 페이지 리다이렉팅 페이지 뼈대 구현"
  package-lock.json
  package.json
  public/index.html
  src/components/home/HomeHeader.vue
  src/components/login/LoginMain.vue
  src/components/login/LoginRedirect.vue
  src/main.js
  src/routers/index.js
Labels: enhancement

#25 결제 수정
  src/components/payment/CheckoutView.vue
  src/components/payment/FailView.vue
  src/components/reservation/ReservationCheckMain.vue
  vue.config.js
Labels: bug

#26 Feat/login 카카오 로그인 리다이렉팅 페이지 구현
  package-lock.json
  public/index.html
  src/components/login/LoginMain.vue
  src/components/login/LoginRedirect.vue
  src/routers/index.js
Labels: enhancement

#33 Feat : "방 등록 페이지 구현"
  package.json
  src/components/home/HomeHeader.vue
  src/components/room/RoomCreate.vue
  src/components/room/RoomList.vue
  src/routers/index.js
Labels: enhancement

#37 Feat : "룸 검색 기능 구현"
  package.json
  src/components/room/RoomList.vue
  src/components/room/RoomSearch.vue
  src/main.js
Labels: enhancement

#42 Feat/create room
  src/components/room/RoomCreate.vue
  vue.config.js
Labels: enhancement

#43 Feat/Payment Success
  src/components/payment/CheckoutView.vue
  src/components/payment/SuccessView.vue
  src/routers/index.js
Labels: enhancement

#45 Feat/불필요한 데이터 삭제
  src/components/payment/SuccessView.vue
Labels: enhancement

#47 Feat/화면 수정
  src/components/payment/SuccessView.vue
Labels: bug

#49 Fix : "메인 페이지 이미지 에러 수정"
  src/components/room/RoomCreate.vue
  src/components/room/RoomList.vue
  vue.config.js
Labels: bug

#51 Feat/room detail
  package.json
  src/components/home/HomeMain.vue
  src/components/reservation/ReservationCheckMain.vue
  src/components/room/RoomList.vue
  src/components/roomdetail/RoomDetailHeader.vue
  src/components/roomdetail/RoomDetailMain.vue
  src/components/roomdetail/RoomLike.vue
  src/components/roomdetail/RoomReservation.vue
  src/main.js
  src/scss/_override.scss
  src/scss/style.scss
  src/scss/variables.scss
Labels: enhancement

#52 Feat/filter room
  src/components/home/HomeMain.vue
  src/components/room/RoomCreate.vue
  src/components/room/RoomFilter.vue
  src/components/room/RoomList.vue
  src/components/room/RoomSearch.vue
Labels: enhancement

#54 Feat: "로그인 성공시 유저 정보 로컬스토리지에 저장"
  src/components/login/LoginRedirect.vue
Labels: enhancement

#41 Feat : “유저 정보 조회 및 권한 수정”
  src/components/userdetail/UserDetailMain.vue
Labels: enhancement

#56 Fix: "로그인, 로그아웃 리다이렉팅 url 수정"
  src/components/home/HomeHeader.vue
  src/components/login/LoginMain.vue
Labels: bug

#57 Fix: "네트리파이 리다이렉트 오류 문제"
  public/_redirects
Labels: bug

#60 Fix: "로그아웃 버튼 문제 해결"
  src/components/Logout/LogoutRedirect.vue
  src/components/home/HomeHeader.vue
  src/components/login/LoginMain.vue
Labels: bug

#66 Feat/Payment: 결제 화면 CSS 적용
  src/components/payment/CheckoutView.vue
  src/components/payment/SuccessView.vue
Labels: enhancement

#68 Feat/Payment: 결제 화면 문구 작성 및 수정
  src/components/payment/CheckoutView.vue
  src/components/payment/SuccessView.vue
Labels: enhancement

#65 Feat : “유저 정보 수정 구현”
  src/components/updateuserinfo/UpdateUserInfoHeader.vue
  src/components/updateuserinfo/UpdateUserInfoMain.vue
  src/components/userdetail/UserDetailMain.vue
  src/routers/index.js
Labels: enhancement

#70 Fix: "서버 배포로 인한 url 수정"
  src/components/home/HomeHeader.vue
  src/components/login/LoginMain.vue
  src/components/login/LoginRedirect.vue
  src/components/payment/SuccessView.vue
  src/components/room/RoomCreate.vue
  src/components/room/RoomList.vue
  src/components/room/RoomSearch.vue
  src/components/roomdetail/RoomDetailFooter.vue
  src/components/roomdetail/RoomDetailMain.vue
  src/components/updateuserinfo/UpdateUserInfoMain.vue
  src/components/userdetail/UserDetailMain.vue
Labels: bug

#72 Feat: "build 폴더 생성"
  .gitignore
  dist/_redirects
  dist/css/app.b73daa12.css
  dist/css/chunk-vendors.7c517d0a.css
  dist/favicon-96x96.png
  dist/favicon.ico
  dist/fonts/materialdesignicons-webfont.21f691f0.ttf
  dist/fonts/materialdesignicons-webfont.54b0f60d.woff2
  dist/fonts/materialdesignicons-webfont.5d875350.eot
  dist/fonts/materialdesignicons-webfont.d671cbf6.woff
  dist/index.html
  dist/js/app.317d1c85.js
  dist/js/app.317d1c85.js.map
  dist/js/chunk-vendors.7f88cdce.js
  dist/js/chunk-vendors.7f88cdce.js.map
  dist/js/webfontloader.04413dfc.js
  dist/js/webfontloader.04413dfc.js.map
Labels: enhancement

#73 Feat: "S3 Github actions으로 CD 구축"
  .github/workflows/CI.yml
  .gitignore
  dist/index.html
  dist/js/app.317d1c85.js
  dist/js/app.317d1c85.js.map
  src/components/home/HomeHeader.vue
Labels: enhancement

#74 Fix: "develop 브랜치로 수정"
  .github/workflows/CI.yml
Labels: enhancement

#76 Fix: "Login Logout redirect url 수정"
  .github/workflows/CI.yml
  src/components/home/HomeHeader.vue
  src/components/login/LoginMain.vue
Labels: enhancement

#78 Fix: "User 권한 변경시 LocalStorage 정보 수정"
  src/components/updateuserinfo/UpdateUserInfoMain.vue
Labels: bug

#80 Fix: "Room Category 메뉴 리스트 오류 수정"
  src/components/room/RoomList.vue
  src/components/room/RoomSearch.vue
Labels: bug

#89 Fix: "Https 사이트에서 Http에 요청으로 인해 생긴 Mixed content 이슈 해결 "
  public/index.html
Labels: bug

#90 Refactor: "route53을 통한 도메인 연결로 인한 변경" "
  .env
  public/index.html
Labels: bug

#93 Feat/userdetail
  src/App.vue
  src/components/home/HomeHeader.vue
  src/components/login/LoginHeader.vue
  src/components/reservation/ReservationCheckHeader.vue
  src/components/reservationlist/ReservationListMain.vue
  src/components/roomdetail/RoomDetailHeader.vue
  src/components/roomdetail/RoomDetailMain.vue
  src/components/roomlist/RoomListMain.vue
  src/components/sidebar/SidebarHeader.vue
  src/components/sidebar/UserSidebar.vue
  src/components/sidebar/sidebarItem.json
  src/components/userdetail/UserDetailHeader.vue
  src/components/userdetail/UserDetailMain.vue
  src/routers/index.js
  src/scss/_override.scss
  src/scss/_sidebar.scss
  src/scss/style.scss
Labels: enhancement

#95 feat: "swal 추가"
  package.json
  src/components/dialog/AlertDialog.vue
  src/components/roomdetail/RoomDetailFooter.vue
  src/main.js
Labels: enhancement

#98 Feat/edit room
  package.json
  src/components/reservationlist/ReservationListMain.vue
  src/components/room/RoomCreate.vue
  src/components/room/RoomEdit.vue
  src/components/roomdetail/RoomDetailFooter.vue
  src/components/roomdetail/RoomDetailMain.vue
  src/components/roomdetail/RoomReservation.vue
  src/components/roomlist/RoomListMain.vue
  src/components/sidebar/sidebarItem.json
  src/components/unit/CustomDatePicker.vue
  src/main.js
  src/routers/index.js
Labels: enhancement

#99 Refactor: "Https 설정으로 인한 변경"
  .env
  src/components/login/LoginRedirect.vue
  src/components/reservationlist/ReservationListMain.vue
  src/components/userdetail/UserDetailMain.vue
Labels: bug, enhancement

#100 Refactor: "배포 URL 수정"
  .env
Labels: bug

#105 Feat: "예약하기 선택 시 메세지 출력"
  src/components/roomdetail/RoomDetailMain.vue
  src/components/roomdetail/RoomReservation.vue
  src/components/unit/CustomDatePicker.vue
Labels: enhancement

#107 Feat: "User 로그인 이후 추가 정보 받는 페이지 추가"
  public/index.html
  src/components/login/LoginDetail.vue
  src/components/login/LoginRedirect.vue
  src/main.js
  src/routers/index.js
Labels: enhancement, refactor

#109 Docs: "package.json 추가"
  package.json
Labels: duplicate

#113 Refactor/user info
  src/components/updateuserinfo/UpdateUserInfoMain.vue
  src/components/userdetail/UserDetailMain.vue
Labels: enhancement, refactor

#117 Feat: "좋아요 버튼 기능 구현"
  src/components/roomdetail/RoomDetailFooter.vue
  src/components/roomdetail/RoomDetailMain.vue
  src/components/roomdetail/RoomLike.vue
  src/main.js
Labels: enhancement

#116 Feat: "휴무 로직 추가"
  src/components/home/HomeFooter.vue
  src/components/reservationlist/ReservationListMain.vue
  src/components/reservationlist/ReservationListRoom.vue
  src/components/restschedule/RestScheduleListRoom.vue
  src/components/room/RoomEdit.vue
  src/components/room/RoomList.vue
  src/components/roomdetail/RoomDetailMain.vue
  src/components/roomdetail/RoomReservation.vue
  src/components/unit/CustomDatePicker.vue
  src/routers/index.js
Labels: bug, enhancement

#115 Fix: "예약페이지 삭제 및 결제 화면 수정"
  src/components/payment/CheckoutView.vue
  src/components/payment/SuccessView.vue
  src/components/reservation/ReservationCheckHeader.vue
  src/components/reservation/ReservationCheckMain.vue
  src/routers/index.js
Labels: bug, refactor

#123 Refactor: user 네임 칸 생성
  src/components/userdetail/UserDetailMain.vue
Labels: refactor

#125 Refactor: 방등록 주소 검색으로 수정
  src/components/room/RoomCreate.vue
Labels: enhancement

#126 Feat: 방 검색 필터 초기화 버튼 추가
  src/components/room/RoomSearch.vue
Labels: enhancement
