Repository AirDnS/airDns-front, pull requests merged in 2024-02, with the labels that each got.

#131 Refactor: 결제화면에서 쿠폰 삭제
  src/components/payment/CheckoutView.vue
Labels: refactor

#134 Feat: "지도 검색 기능 추가"
  public/index.html
  src/components/room/RoomCreate.vue
  src/components/room/RoomList.vue
  src/components/room/RoomSearch.vue
Labels: enhancement

#135 Feature/locationsearch
  src/components/room/RoomList.vue
Labels: bug, enhancement

#136 Feat: "거리 확장 검색 추가"
  src/components/room/RoomList.vue
Labels: enhancement
